-- HaynesPro chassis crawl → catalog ingest
-- Source crawl: scrapers/output/haynespro-crawl-q5-fy-2026-05-23.json
-- HaynesPro modelId: d_319001449 (Q5 (FY))
-- Crawl fetched_at: 2026-05-23T08:26:13.641Z
-- Target catalog generation_id: 82
-- Engines: DEUB, DEZB, DETB, DEUA, DEZE, DESA, DETA, DFBA, CVMD, DCPE, DAXB, DAYB, DAXC, DNTA, DCPC, CWGD, DEWB
-- Generated by scrapers/haynespro/ingest_to_sql.ts on 2026-05-23T09:30:03.555Z

SET NAMES utf8mb4;

-- 1. HaynesPro source row (is_public=0, citation only for audit trail)
INSERT IGNORE INTO sources (citation, url, retrieved_at, notes, is_public, public_link) VALUES
  ('HaynesPro WorkshopData — Q5 (FY)', 'https://www.workshopdata.com/touch/site/layout/modelTypesList?modelId=d_319001449', NOW(), 'Auto-ingested via scrapers/haynespro/ingest_to_sql.ts. modelId d_319001449, 17 engines crawled, 17 unique engine codes ingested.', 0, 0);
SET @s_haynes := (SELECT id FROM sources WHERE url = 'https://www.workshopdata.com/touch/site/layout/modelTypesList?modelId=d_319001449' ORDER BY id DESC LIMIT 1);

-- 2. Engines — auto-insert any not yet in catalog
INSERT IGNORE INTO engines (code, display_name, displacement_cc, fuel, aspiration, cylinders) VALUES
  ('DEUB', '30 TDI (DEUB) 100kW', 1968, 'diesel', 'turbo', NULL),
  ('DEZB', '30 TDI (DEZB) 100kW', 1968, 'diesel', 'turbo', NULL),
  ('DETB', '35 TDI (DETB) 120kW', 1968, 'diesel', 'turbo', NULL),
  ('DEUA', '35 TDI (DEUA) 110kW', 1968, 'diesel', 'turbo', NULL),
  ('DEZE', '35 TDI (DEZE) 120kW', 1968, 'diesel', 'turbo', NULL),
  ('DESA', '40 TDI (DESA) 140kW', 1968, 'diesel', 'turbo', NULL),
  ('DETA', '40 TDI (DETA) 140kW', 1968, 'diesel', 'turbo', NULL),
  ('DFBA', '40 TDI (DFBA) 150kW', 1968, 'diesel', 'turbo', NULL),
  ('CVMD', '45 TDI (CVMD) 183kW', 2967, 'diesel', 'turbo', NULL),
  ('DCPE', '45 TDI (DCPE) 170kW', 2967, 'diesel', 'turbo', NULL),
  ('DAXB', '45 TFSI (DAXB) 185kW', 1984, 'petrol', 'turbo', NULL),
  ('DAYB', '45 TFSI (DAYB) 185kW', 1984, 'petrol', 'turbo', NULL),
  ('DAXC', '45 TFSI (DAXC) 183kW', 1984, 'petrol', 'turbo', NULL),
  ('DNTA', '45 TFSI (DNTA) 180kW', 1984, 'petrol', 'turbo', NULL),
  ('DCPC', '50 TDI (DCPC) 210kW', 2967, 'diesel', 'turbo', NULL),
  ('CWGD', '55 TFSI (CWGD) 260kW', 2995, 'petrol', 'turbo', NULL),
  ('DEWB', 'SQ5 (3.0 TDI) MHEV (DEWB) 255kW', 2967, 'hybrid', 'turbo', NULL);

-- 3. fluid_specs — engine_oil + coolant scoped to gen_id 82
SET @gen := 82;

INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DEUB'), 4.7, 4.97, '0W-30', 'VW 507 00', 'HaynesPro typeId t_319005453; 30 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DEUB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DEUB'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005453; 30 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DEUB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DEZB'), 5.5, 5.81, '0W-20', 'VW 509 00', 'HaynesPro typeId t_619017262; 30 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DEZB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DEZB'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619017262; 30 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DEZB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DETB'), 4.7, 4.97, '0W-30', 'VW 507 00', 'HaynesPro typeId t_319005451; 35 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DETB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DETB'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005451; 35 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DETB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DEUA'), 4.7, 4.97, '0W-30', 'VW 507 00', 'HaynesPro typeId t_319005452; 35 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DEUA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DEUA'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005452; 35 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DEUA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DEZE'), 5.5, 5.81, '0W-20', 'VW 509 00', 'HaynesPro typeId t_619029454; 35 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DEZE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DEZE'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619029454; 35 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DEZE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DESA'), 4.7, 4.97, '0W-30', 'VW 507 00', 'HaynesPro typeId t_319005449; 40 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DESA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DESA'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005449; 40 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DESA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DETA'), 4.7, 4.97, '0W-30', 'VW 507 00', 'HaynesPro typeId t_319005450; 40 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DETA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DETA'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005450; 40 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DETA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DFBA'), 5.5, 5.81, '0W-20', 'VW 509 00', 'HaynesPro typeId t_619017263; 40 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DFBA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DFBA'), 8, 8.45, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619017263; 40 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DFBA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'CVMD'), 6.1, 6.45, '0W-30', 'VW 507 00', 'HaynesPro typeId t_619017258; 45 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'CVMD'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'CVMD'), 15, 15.85, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619017258; 45 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'CVMD'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DCPE'), 6.1, 6.45, '0W-30', 'VW 507 00', 'HaynesPro typeId t_619017259; 45 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DCPE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DCPE'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619017259; 45 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DCPE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DAXB'), 5.2, 5.49, '0W-30', 'VW 504 00', 'HaynesPro typeId t_319005448; 45 TFSI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DAXB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DAXB'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005448; 45 TFSI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DAXB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DAYB'), 5.2, 5.49, '0W-30', 'VW 502 00', 'HaynesPro typeId t_319005530; 45 TFSI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DAYB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DAYB'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005530; 45 TFSI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DAYB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DAXC'), 5.2, 5.49, '0W-30', 'VW 502 00', 'HaynesPro typeId t_319005529; 45 TFSI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DAXC'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DAXC'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005529; 45 TFSI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DAXC'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DNTA'), 5.2, 5.49, '0W-20', 'VW 508 00', 'HaynesPro typeId t_619016909; 45 TFSI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DNTA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DNTA'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619016909; 45 TFSI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DNTA'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DCPC'), 6.1, 6.45, '0W-30', 'VW 507 00', 'HaynesPro typeId t_619007998; 50 TDI; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DCPC'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DCPC'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619007998; 50 TDI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DCPC'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'CWGD'), 7.25, 7.66, '0W-20', 'VW 508 00', 'HaynesPro typeId t_319005447; 55 TFSI; drain ? Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'CWGD'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'CWGD'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_319005447; 55 TFSI'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'CWGD'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'DEWB'), 6.1, 6.45, '0W-30', 'VW 507 00', 'HaynesPro typeId t_619017260; SQ5 (3.0 TDI) MHEV; drain 30 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'DEWB'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'DEWB'), 10, 10.57, NULL, 'TL-VW 774L (G12EVO)', 'HaynesPro typeId t_619017260; SQ5 (3.0 TDI) MHEV'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'DEWB'));

-- 4. spec_sources — link inserted fluid_specs rows to the HaynesPro source
INSERT IGNORE INTO spec_sources (spec_table, spec_id, source_id)
SELECT 'fluid_specs', fs.id, @s_haynes
FROM fluid_specs fs
JOIN engines e ON e.id = fs.engine_id
WHERE fs.generation_id = @gen
  AND e.code IN ('DEUB', 'DEZB', 'DETB', 'DEUA', 'DEZE', 'DESA', 'DETA', 'DFBA', 'CVMD', 'DCPE', 'DAXB', 'DAYB', 'DAXC', 'DNTA', 'DCPC', 'CWGD', 'DEWB')
  AND fs.fluid_type IN ('engine_oil', 'coolant');

-- 5. Audit
SELECT e.code, COUNT(fs.id) AS rows_count,
       GROUP_CONCAT(DISTINCT CONCAT(fs.fluid_type, ' ', fs.capacity_l, 'L ', COALESCE(fs.viscosity,''), ' ', COALESCE(fs.spec_standard,'')) SEPARATOR ' | ') AS specs
FROM fluid_specs fs
JOIN engines e ON e.id = fs.engine_id
WHERE fs.generation_id = @gen
  AND e.code IN ('DEUB', 'DEZB', 'DETB', 'DEUA', 'DEZE', 'DESA', 'DETA', 'DFBA', 'CVMD', 'DCPE', 'DAXB', 'DAYB', 'DAXC', 'DNTA', 'DCPC', 'CWGD', 'DEWB')
GROUP BY e.code ORDER BY e.code;
