-- HaynesPro chassis crawl → catalog ingest
-- Source crawl: scrapers/output/haynespro-crawl-toyota-camry-xv70-2026-05-23.json
-- HaynesPro modelId: d_319001688 (Camry (XV70))
-- Crawl fetched_at: 2026-05-23T09:16:26.675Z
-- Target catalog generation_id: 2
-- Engines: 6AR-FSE, A25A-FKS, 2AR-FE, A25A-FXS, 2GR-FKS
-- Generated by scrapers/haynespro/ingest_to_sql.ts on 2026-05-23T09:30:12.231Z

SET NAMES utf8mb4;

-- 1. HaynesPro source row (is_public=0, citation only for audit trail)
INSERT IGNORE INTO sources (citation, url, retrieved_at, notes, is_public, public_link) VALUES
  ('HaynesPro WorkshopData — Camry (XV70)', 'https://www.workshopdata.com/touch/site/layout/modelTypesList?modelId=d_319001688', NOW(), 'Auto-ingested via scrapers/haynespro/ingest_to_sql.ts. modelId d_319001688, 5 engines crawled, 5 unique engine codes ingested.', 0, 0);
SET @s_haynes := (SELECT id FROM sources WHERE url = 'https://www.workshopdata.com/touch/site/layout/modelTypesList?modelId=d_319001688' ORDER BY id DESC LIMIT 1);

-- 2. Engines — auto-insert any not yet in catalog
INSERT IGNORE INTO engines (code, display_name, displacement_cc, fuel, aspiration, cylinders) VALUES
  ('6AR-FSE', '2.0 (6AR-FSE) 110kW', 1998, 'petrol', 'NA', NULL),
  ('A25A-FKS', '2.5 (A25A-FKS) 152kW', 2487, 'petrol', 'NA', NULL),
  ('2AR-FE', '2.5 (2AR-FE) 130kW', 2494, 'petrol', 'NA', NULL),
  ('A25A-FXS', '2.5 Hybrid (A25A-FXS) 160kW', 2487, 'hybrid', 'NA', NULL),
  ('2GR-FKS', '3.5 (2GR-FKS) 183kW', 3456, 'petrol', 'NA', NULL);

-- 3. fluid_specs — engine_oil + coolant scoped to gen_id 2
SET @gen := 2;

INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = '6AR-FSE'), 4.6, 4.86, '0W-20', 'API SN', 'HaynesPro typeId t_619029738; 2.0; drain 40 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = '6AR-FSE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = '6AR-FSE'), 7.2, 7.61, NULL, 'Toyota Super Longlife Coolant', 'HaynesPro typeId t_619029738; 2.0'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = '6AR-FSE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'A25A-FKS'), 4.5, 4.76, '0W-16', 'API SN', 'HaynesPro typeId t_619020126; 2.5; drain 40 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'A25A-FKS'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'A25A-FKS'), 6.9, 7.29, NULL, 'Toyota Super Longlife Coolant', 'HaynesPro typeId t_619020126; 2.5'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'A25A-FKS'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = '2AR-FE'), 4.4, 4.65, '0W-20', 'API SN', 'HaynesPro typeId t_619011361; 2.5; drain 40 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = '2AR-FE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = '2AR-FE'), 6.6, 6.97, NULL, 'Toyota Super Longlife Coolant', 'HaynesPro typeId t_619011361; 2.5'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = '2AR-FE'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = 'A25A-FXS'), 4.5, 4.76, '0W-16', 'API SN', 'HaynesPro typeId t_319007789; 2.5 Hybrid; drain 40 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = 'A25A-FXS'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = 'A25A-FXS'), NULL, NULL, NULL, 'Toyota Super Longlife Coolant', 'HaynesPro typeId t_319007789; 2.5 Hybrid'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = 'A25A-FXS'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'engine_oil', (SELECT id FROM engines WHERE code = '2GR-FKS'), NULL, NULL, '0W-20', 'API SP', 'HaynesPro typeId t_619029739; 3.5; drain 40 Nm'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'engine_oil' AND engine_id = (SELECT id FROM engines WHERE code = '2GR-FKS'));
INSERT INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes)
SELECT @gen, 'coolant', (SELECT id FROM engines WHERE code = '2GR-FKS'), NULL, NULL, NULL, 'Toyota Super Longlife Coolant', 'HaynesPro typeId t_619029739; 3.5'
WHERE NOT EXISTS (SELECT 1 FROM fluid_specs WHERE generation_id = @gen AND fluid_type = 'coolant' AND engine_id = (SELECT id FROM engines WHERE code = '2GR-FKS'));

-- 4. spec_sources — link inserted fluid_specs rows to the HaynesPro source
INSERT IGNORE INTO spec_sources (spec_table, spec_id, source_id)
SELECT 'fluid_specs', fs.id, @s_haynes
FROM fluid_specs fs
JOIN engines e ON e.id = fs.engine_id
WHERE fs.generation_id = @gen
  AND e.code IN ('6AR-FSE', 'A25A-FKS', '2AR-FE', 'A25A-FXS', '2GR-FKS')
  AND fs.fluid_type IN ('engine_oil', 'coolant');

-- 5. Audit
SELECT e.code, COUNT(fs.id) AS rows_count,
       GROUP_CONCAT(DISTINCT CONCAT(fs.fluid_type, ' ', fs.capacity_l, 'L ', COALESCE(fs.viscosity,''), ' ', COALESCE(fs.spec_standard,'')) SEPARATOR ' | ') AS specs
FROM fluid_specs fs
JOIN engines e ON e.id = fs.engine_id
WHERE fs.generation_id = @gen
  AND e.code IN ('6AR-FSE', 'A25A-FKS', '2AR-FE', 'A25A-FXS', '2GR-FKS')
GROUP BY e.code ORDER BY e.code;
