-- mig 342 — Q5 FY (gen_id 82) cleanup: replace v1-parser junk with new clean rows.
--   torque_specs: drop 105 v1 rows (notes='HaynesPro adjustmentData' from mig 341),
--                 insert 403 unique torques from new line-aware parser.
--   service_intervals: drop 33 interval-header rows from mig 341,
--                 insert 37 per-item rows mapped to snake_case codes.

SET NAMES utf8mb4;

-- 1. Resolve existing HaynesPro source ID
SET @s_haynes := (SELECT id FROM sources WHERE url = 'https://www.workshopdata.com/touch/site/layout/modelTypesList?modelId=d_319001449' ORDER BY id DESC LIMIT 1);

-- 2. DELETE v1 junk torque rows
DELETE ss FROM spec_sources ss JOIN torque_specs ts ON ts.id = ss.spec_id WHERE ss.spec_table = 'torque_specs' AND ts.generation_id = 82 AND ts.notes = 'HaynesPro adjustmentData';
DELETE FROM torque_specs WHERE generation_id = 82 AND notes = 'HaynesPro adjustmentData';

-- 3. DELETE v1 interval-header service rows
DELETE ss FROM spec_sources ss JOIN service_intervals si ON si.id = ss.spec_id WHERE ss.spec_table = 'service_intervals' AND si.generation_id = 82 AND si.notes LIKE 'HaynesPro modelDetailMaintenance%';
DELETE FROM service_intervals WHERE generation_id = 82 AND notes LIKE 'HaynesPro modelDetailMaintenance%';

-- 4. INSERT 403 clean torque rows
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head Stage 1 Stage 2', 70, 52, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Valve cover', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Bolts 1 - 20) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Bolts 1 - 20) (Bolts A)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Engine oil drain plug', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil filter', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Injector (Renew the washer and O-ring) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Glow plugs', 17, 13, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Glow plugs', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft position sensor', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oxygen sensor', 55, 41, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter motor (M12) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter motor (M10)', 65, 48, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft bearing caps Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft gearwheel', 100, 74, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft gearwheel Stage 1', 180, 133, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley Stage 1', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt tensioner pulley Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt tensioner pulley (Stud bolt)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt idler pulley (B) (if damaged or stretched)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt idler pulley', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Drive plate Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold Stage 1', 11, 8, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold Stage 1 Stage 2', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold Stage 1 Stage 2', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump gearwheel (Nut)', 95, 70, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (Renew the bolts) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (Bracket)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (to turbocharger)', 16, 12, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (to engine block) (Renew the seals)', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (to turbocharger) (Renew the seal)', 14, 10, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (to engine block) (Renew the', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'EGR valve', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump Stage 1', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Manual transmission filler plug', 45, 33, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Manual transmission drain plug', 45, 33, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clutch pressure plate (Renew the bolts) Stage 1', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Front drive shaft to wheel bearing housing (Renew the bolt)', 200, 148, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Rear drive shaft to wheel bearing housing (Renew the bolt)', 200, 148, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wheel bolts Stage 1 Stage 2', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wheel bolts Stage 1 Stage 2', 140, 103, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tyre pressure sensor (Renew the bolt)', 4, 3, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Steering wheel (Renew the bolt) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Aluminium bolts; renew the bolts)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Steel bolts)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) (All bolts)', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Lower section) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Engine oil drain plug (Renew the seal)', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oxygen sensor', 52, 38, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'NOx sensor', 52, 38, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator (Aluminium bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft bearing caps Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt tensioner pulley (Nut) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt idler pulley Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Dual mass flywheel (To drive plate)', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold (Bolts 1 - 10) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump gearwheel', 95, 70, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (to turbocharger)', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (to engine block) (Renew the seal)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (to turbocharger) (Renew the', 14, 10, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (to engine block) (Renew the', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Dual-clutch transmission filler plug (Renew the filler plug)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Gearbox hydraulic control unit filler plug (Aluminium sump;', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Gearbox hydraulic control unit drain plug (Aluminium sump;', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head (Renew the bolts) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head (Renew the bolts) Stage 1', 70, 52, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap (Renew the bolts) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wait for 30 minutes before refilling the engine with oil (All', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wait for 30 minutes before refilling the engine with oil (All', 13, 10, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Engine oil drain plug (Metal sump)', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil filter (Renew the O-ring)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft position sensor (Renew the seal)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter/alternator', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator (Without sliding bushes) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator (With sliding bushes)', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wait for 30 minutes before refilling the engine with oil Stage', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft gearwheel (Renew the bolt) Stage 1', 180, 133, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Renew the bolts) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner mounting bracket (Renew the', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt idler pulley (Renew the bolt) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Drive plate (Renew the bolts) Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold (Renew the gasket) Stage 1', 11, 8, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold (Renew the gasket) Stage 1', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump (Renew the bolts) (Lubricate the seal with clean', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (to turbocharger) (Renew the seal)', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel injector side)', 28, 21, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel rail side)', 28, 21, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel pump side)', 28, 21, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'EGR valve (Inlet side; renew the seal)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'EGR valve (Exhaust side; renew the seal)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump (Renew the bolts) Stage 1', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Steering wheel (Renew the bolt)', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter/alternator (Stud bolt)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter/alternator (Bolts)', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Flywheel Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump (Lubricate the seal with clean coolant) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'EGR valve (Renew the gasket)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Aluminium) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Steel)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel filter (Nut)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Injector (Renew the washer and O-ring) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Glow plugs (Without pressure sensor)', 17, 13, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Glow plugs (With pressure sensor)', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (Short bolts) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (Long bolts) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line', 16, 12, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line', 14, 10, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential filler plug', 16, 12, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential drain plug', 16, 12, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt tensioner pulley (Stud bolt) Stage 1', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing belt tensioner pulley (Stud bolt) (Nut)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump Stage 1 Stage 2', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head (Renew the bolts and gasket) (Bolts 1 - 10)', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Valve cover (Renew the bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap (Renew the bolts) Stage 1', 45, 33, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Main bearing cap (Renew the bolts) (Bolts 1 - 10)', 65, 48, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, lower section (Renew the bolts, gasket and O-ring) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, upper section (Bolts (type 1)) (Bolts 1 - 18)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, upper section (Bolts (type 2)) (Bolts 1 - 13)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ignition coil (Nut)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ignition coil (Stud bolt)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel pressure sensor', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Knock sensor', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oxygen sensor', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter/alternator (Renew the bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft gearwheel (Left-hand thread)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (M16 x 75) (Renew the O-ring)', 100, 74, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (M16 x 105) (Renew the O-ring)', 240, 177, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner (Renew the bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft chain tensioner (Renew the chain tensioner, if', 85, 63, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft chain guide (Bolts A)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft chain guide (Bolt B)', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft chain tensioner guide', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner guide', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain guide (Upper)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain guide (Lower)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover, upper section (Renew the O-rings) Stage 1', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold (Renew the seal)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump (Renew the gasket)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump gearwheel (Left-hand thread)', 17, 13, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail (Renew the bolts) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (Renew the O-ring) Stage 1', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coat the thread with high-temperature grease (Nuts 1 and 2)', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Stud bolt; used cylinder head)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Stud bolt; new cylinder head)', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line (Renew the O-ring)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (To engine block)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (To turbocharger)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel rail side) Stage 1 Stage 2', 40, 30, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel pump side) Stage 1 Stage 2', 40, 30, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump (Aluminium bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump (Steel bolts) Stage 1', 16, 12, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump chain tensioner', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Haldex coupling filler plug (Renew the filler plug)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Haldex coupling drain plug (Renew the drain plug)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head Stage 1 Stage 2', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Valve cover', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap Stage 1', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Main bearing cap Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Main bearing cap Stage 1 Stage 2', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Lower section) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Injector Stage 1', 6, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft bearing caps (Bolts 1 - 4) Stage 1', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft bearing caps (Bolts 1 - 4) (Bolts 1 - 8)', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft gearwheel', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley Stage 1', 150, 111, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft gearwheel', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner guide Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain guide Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover (Upper section) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover (Lower section) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover (Lower section) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Flexplate (Clean the contact surfaces) Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold Stage 1 Stage 2', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold (Bolts 1 - 4) Stage 1', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump (Aluminium bolts) Stage 1', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump (Steel bolts)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (Renew the bolts)', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Bracket) Stage 1', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Bracket) Stage 1', 28, 21, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (M10) (Stud bolt)', 14, 10, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump gearwheel (Renew the bolt) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump chain guide Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump chain tensioner guide Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Automatic transmission filler plug (Renew the filler plug)', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Torque converter (Renew the bolts)', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Transfer box filler plug (Renew the filler plug)', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Transfer box drain plug (Renew the drain plug)', 12, 9, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, front, filler plug', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, front, drain plug', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential filler plug (Renew the filler plug)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential drain plug (Renew the drain plug)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, rear, filler plug', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, rear, drain plug', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head Stage 1 Stage 2', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Lower section) Stage 1', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft position sensor (Aluminium valve cover)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft position sensor (Plastic valve cover)', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft bearing caps Stage 1 Stage 2', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner (With alternator) Stage 1', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner (With starter/alternator) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner (With starter/alternator)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt idler pulley (With alternator)', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Flexplate Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump pulley', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Stud bolt) Stage 1', 14, 10, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump (Renew the bolts and seal) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump gearwheel (Renew the bolts) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump chain guide (Renew the bolts) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump chain tensioner guide (Renew the bolts) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head (Bolt type: 10.9) (Bolts 1 - 10)', 40, 30, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head (Bolt type: 12.9) (Bolts 1 - 10)', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap Stage 1', 45, 33, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Main bearing cap (Bolts 1 - 10) Stage 1', 65, 48, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) (Bolts 1 - 14)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) (Bolts 1 - 18)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Lower section, plastic sump) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Lower section, metal sump) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ignition coil (Bolt)', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft position sensor (Renew the O-ring)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Knock sensor (Renew the bolt) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner (With alternator) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt idler pulley Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft chain tensioner', 85, 63, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner (Renew the bolt) Stage 1', 4, 3, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain guide', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover, upper section', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail (M8) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail (M6)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (M6 bolts; renew the bolts) (M6)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (M6) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (M8)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, rear, level plug', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) (Aluminium bolts)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump (Upper section) (Steel and aluminium bolts)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Spark plugs', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Manual transmission) (Bolt type: 10.9)', 240, 177, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Automatic transmission) (Bolt type: 10.9)', 100, 74, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Automatic transmission) (Bolt type: 8.8)', 150, 111, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt idler pulley (With alternator) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt idler pulley (With starter/alternator)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner (Aluminium bolts) Stage 1', 4, 3, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner (Steel bolts)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Coolant pump gearwheel (Left-hand thread) Stage 1', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil supply line', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential filler plug', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential drain plug', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, rear, filler plug (Renew the filler plug)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Differential, rear, drain plug (Renew the drain plug)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Hydraulic differential control unit filler plug (Renew the', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Hydraulic differential control unit drain plug (Renew the drain', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wait for 30 minutes before starting the engine Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wait for 30 minutes before refilling the engine with oil (Bolts', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wait for 30 minutes before refilling the engine with oil (Bolts', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ignition coil (Bolt)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (M16 x 105) Stage 1', 240, 177, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (M16 x 75) Stage 1', 100, 74, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold (Renew the gasket)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump (Renew the bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces (Bolts 1 - 13) Stage 1', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces (Bolts 1 - 13) (Bolts 14 - 18)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces (Bolts 1 - 18) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Lower section (Plastic sump) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'The component must be fitted within 5 minutes of applying the', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section (Aluminium bolts) (Bolts 1 - 18)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section (Steel and aluminium bolts) (Bolts 1 - 13)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ignition coil (Stud bolt)', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Bolt type: 8.8) Stage 1', 150, 111, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Bolt type: 10.9) Stage 1', 100, 74, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump (M8) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Nuts)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Studs)', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel rail side) Stage 1 Stage 2', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel pump side) Stage 1 Stage 2', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1 Stage 2', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1 Stage 2', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1 Stage 2', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil filter (Renew the seal)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator (Bolts)', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator (Nut)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt idler pulley', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1 Stage 2', 10, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tightening sequence: Stage 1', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Oil pump Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces Stage 1 Stage 2', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces Stage 1 Stage 2', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap (Renew the bolts) Stage 1', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, lower section (Renew the bolts) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, lower section (Renew the bolts) Stage 1', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, upper section (Renew the bolts, seals and O-rings) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Engine oil drain plug (Renew the seal)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Injector (Renew the bolt, washer and O-ring) Stage 1', 6, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft position sensor', 4, 3, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel pressure sensor (Clean the contact surfaces) Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter motor Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter/alternator (Nuts)', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Starter/alternator (Studs)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces Stage 1 Stage 2', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (Renew the bolt) Stage 1', 150, 111, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Ancillary drive belt tensioner', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner (Renew the bolts and O-ring) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner guide (Renew the bolt) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain guide (Renew the bolts) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover, lower section (Renew the bolts and seals) (Bolts', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover, upper section, left side (Renew the bolts and', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover, upper section, right side (Renew the bolts and', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Clean the contact surfaces Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold (Renew the nuts and gasket) Stage 1', 11, 8, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Exhaust manifold (Renew the nuts and gasket) Stage 1', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold, upper section (Renew the seals) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold, lower section (Renew the seals)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump gearwheel (Renew the nut)', 90, 66, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump chain tensioner (Renew the bolts) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump chain tensioner guide (Renew the bolt) Stage', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Nuts 1 and 2) Stage 1', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Renew the studs)', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger support/oil distribution block (Renew the gasket)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Threads lightly oiled Stage 1 Stage 2', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Threads lightly oiled Stage 1 Stage 2', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Valve cover (Clean the contact surfaces) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Engine oil drain plug (Lower section, metal sump)', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Alternator (Steel bolts)', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold (Renew the gasket)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Dual-clutch transmission drain plug (Oil pump; renew the bolts)', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Bolt)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Nut)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Air-conditioning compressor (Stud bolt)', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, upper section (Type 1; renew the bolts) (Bolts 1 - 18)', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump, upper section (Type 2; renew the bolts) (Bolts 1 - 13)', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (8.8 bolt) (Renew the bolt and O-ring) Stage 1', 150, 111, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Crankshaft pulley (10.9 bolt) (Renew the bolt and O-ring) Stage', 100, 74, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Dual mass flywheel (Renew the bolts) Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (to turbocharger) (Renew the', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger oil return line (to engine block) (Renew the', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Cylinder head (Bolts 1 - 8) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Valve cover Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Big-end bearing cap Stage 1', 50, 37, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Main bearing cap (Bolts 1 - 8) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Sump Stage 1', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Knock sensor', 25, 18, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Camshaft gearwheel (Renew the friction disc and O-ring) Stage 1', 30, 22, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner guide', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover (Lower section) (Bolts A)', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing cover (Upper section)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Fuel rail Stage 1 Stage 2', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure pump Stage 1 Stage 2', 20, 15, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger Stage 1', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger Stage 1 Stage 2', 27, 20, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Balance shaft chain tensioner (Apply thread-locking compound)', 85, 63, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Flywheel (Renew the bolts) Stage 1', 60, 44, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Turbocharger (Stud bolt)', 22, 16, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Tyre pressure sensor', 4, 3, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Timing chain tensioner (Renew the bolt) Stage 1', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section (Renew the bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Lower section (Renew the bolts) Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Lower section (Renew the bolts) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Front drive shaft to wheel bearing housing Stage 1', 200, 148, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Rear drive shaft to wheel bearing housing Stage 1', 200, 148, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Wheel bolts', 140, 103, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section Stage 1 Stage 2', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section Stage 1 Stage 2', 5, 4, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Lower section Stage 1', 2, 1, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Lower section Stage 1 Stage 2', 3, 2, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Lower section (Bolts 1 and 4) Stage 1', 23, 17, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section (Left-hand side) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section (Right-hand side) Stage 1', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Upper section Stage 1 Stage 2', 8, 6, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Inlet manifold (Renew the seals)', 9, 7, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'Threads lightly oiled Stage 1', 15, 11, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel injector side) (Used part)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel rail side) (Used part)', 35, 26, 'HaynesPro adjustmentData');
INSERT INTO torque_specs (generation_id, fastener, torque_nm, torque_ftlb, notes) VALUES (82, 'High-pressure fuel pipe (fuel pump side) (Used part)', 35, 26, 'HaynesPro adjustmentData');

-- 5. INSERT 37 per-item service rows
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'fuel_filter', 15000, 9300, 12, 'Renew the fuel filter');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'engine_air_filter', 15000, 9300, 12, 'Renew the air filter');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'timing_belt_replacement', 15000, 9300, 12, 'Renew the timing belt(s)');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'cabin_air_filter', 15000, 9300, 12, 'Renew the dust and pollen filter');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'engine_oil_and_filter', 15000, 9300, 12, 'Renew the engine oil');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'brake_inspection', 15000, 9300, 12, 'Check the brake pad thickness');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'tire_sealant_check', 15000, 9300, 12, 'Check the tyre sealant can expiry date');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'service_indicator_reset', 15000, 9300, 12, 'Reset the service indicator');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'oil_leak_check', 30000, 18600, 24, 'Check for oil leaks');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'engine_visual_inspection', 30000, 18600, 24, 'Check the engine for damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'wiring_inspection', 30000, 18600, 24, 'Check the wiring looms in the engine compartment for damage, wear and chafing');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'fuel_line_inspection', 30000, 18600, 24, 'Check the fuel lines, hoses and connections for leaks and damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'coolant_flush', 30000, 18600, 24, 'Drain/refill the cooling system');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'transmission_at_fluid', 30000, 18600, 24, 'Check the transmission for damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'drive_shaft_inspection', 30000, 18600, 24, 'Renew both front drive shafts');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'steering_inspection', 30000, 18600, 24, 'Check the steering assembly for damage, leaks and wear');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'brake_line_inspection', 30000, 18600, 24, 'Check the brake lines, hoses and connections for leaks and damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'tire_inspection', 30000, 18600, 24, 'Check the tread depth and wear pattern on all the tyres, including the spare');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'suspension_boot_inspection', 30000, 18600, 24, 'Check the condition of the suspension protective boots');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'tire_pressure_check', 30000, 18600, 24, 'Check the tyre pressures; adjust if necessary');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'tpms_reset', 30000, 18600, 24, 'Reset the tyre pressure monitoring system');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'exterior_light_check', 30000, 18600, 24, 'Check the operation of the exterior lights');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'headlight_alignment', 30000, 18600, 24, 'Check the headlight alignment; adjust if necessary');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'luggage_light_check', 30000, 18600, 24, 'Check the luggage compartment light(s)');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'instrument_cluster_check', 30000, 18600, 24, 'Check the operation of the instrument cluster');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'interior_warning_check', 30000, 18600, 24, 'Check the operation of the interior warning lights');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'horn_check', 30000, 18600, 24, 'Check the operation of the horn');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'wiper_blades', 30000, 18600, 24, 'Check the windscreen wipers and washing system');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'wiper_park_check', 30000, 18600, 24, 'Check the windscreen wiper park position');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'headlight_washer_check', 30000, 18600, 24, 'Check the headlight washing system');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'door_hinge_lube', 30000, 18600, 24, 'Check/lubricate the door hinges');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'underbody_inspection', 30000, 18600, 24, 'Check the underbody protective coating for corrosion and damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'engine_cover_inspection', 30000, 18600, 24, 'Check the engine lower cover for damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'body_corrosion_check', 30000, 18600, 24, 'Check the body for corrosion and damage');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'first_aid_check', 30000, 18600, 24, 'Check the first-aid kit');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'warning_triangle_check', 30000, 18600, 24, 'Check for the presence of a warning triangle');
INSERT INTO service_intervals (generation_id, service, km_normal, miles_normal, months, notes) VALUES (82, 'test_drive', 30000, 18600, 24, 'Test drive');

-- 6. Citations
INSERT IGNORE INTO spec_sources (spec_table, spec_id, source_id) SELECT 'torque_specs', id, @s_haynes FROM torque_specs WHERE generation_id = 82 AND notes = 'HaynesPro adjustmentData';
INSERT IGNORE INTO spec_sources (spec_table, spec_id, source_id) SELECT 'service_intervals', id, @s_haynes FROM service_intervals WHERE generation_id = 82 AND (notes = 'HaynesPro maintenanceSchedule' OR notes IS NOT NULL);

-- Audit
SELECT 'torque_specs' AS spec, COUNT(*) FROM torque_specs WHERE generation_id = 82 UNION ALL SELECT 'service_intervals', COUNT(*) FROM service_intervals WHERE generation_id = 82;