-- 563: Fuse boxes for Opel Corsa F (518) and Insignia B (520), restated from
-- workshop electrical data. Widen amperage to decimal(4,1) first (these cars use
-- 7.5 A and 2 A fuses that smallint can't hold). Vendor-neutral sources 1682/1683.

ALTER TABLE fuses MODIFY COLUMN amperage decimal(4,1) DEFAULT NULL;

-- ───────────────────────── Corsa F (518) ──────────────────────────────────
INSERT INTO fuses (generation_id, location, position, amperage, circuit_name, is_relay) VALUES
(518, 'engine_bay', 'F1', 40, 'Air-conditioning control', 0),
(518, 'engine_bay', 'F2', 50, 'Brake vacuum pump', 0),
(518, 'engine_bay', 'F3', 80, 'Fuse box in passenger compartment', 0),
(518, 'engine_bay', 'F4', 30, 'ESP control unit', 0),
(518, 'engine_bay', 'F5', 70, 'Fuse and relay box in passenger compartment', 0),
(518, 'engine_bay', 'F6', 60, 'Cooling fan control unit; Cooling fan relay', 0),
(518, 'engine_bay', 'F7', 80, 'Fuse and relay box in passenger compartment', 0),
(518, 'engine_bay', 'F8', 20, 'Engine control unit; Fuel pump', 0),
(518, 'engine_bay', 'F9', 15, 'NOx sensor; Coolant sensor; Engine control unit', 0),
(518, 'engine_bay', 'F10', 15, 'Engine control unit', 0),
(518, 'engine_bay', 'F11', 20, 'Engine control unit', 0),
(518, 'engine_bay', 'F12', 5, 'Additional socket; Fan assembly supply relay', 0),
(518, 'engine_bay', 'F13', 5, 'Feed to built-in systems interface', 0),
(518, 'engine_bay', 'F14', 5, 'Battery sensor', 0),
(518, 'engine_bay', 'F15', 20, 'Fuse and relay box in engine compartment', 0),
(518, 'engine_bay', 'F16', 15, 'Right headlight', 0),
(518, 'engine_bay', 'F17', 10, 'NOx sensor; Engine control unit', 0),
(518, 'engine_bay', 'F18', 10, 'Right headlight, main beam', 0),
(518, 'engine_bay', 'F19', 10, 'Left headlight, main beam', 0),
(518, 'engine_bay', 'F20', 30, 'Engine control unit; Fuel pump; Diesel fuel preheater', 0),
(518, 'engine_bay', 'F21', 30, 'Fuse and relay box in engine compartment, relay R3', 0),
(518, 'engine_bay', 'F22', 15, 'Automatic gearbox', 0),
(518, 'engine_bay', 'F23', 5, 'Relay box in passenger compartment, relay R2', 0),
(518, 'engine_bay', 'F24', 40, 'Spare fuse', 0),
(518, 'engine_bay', 'F25', 40, 'Fuse box in passenger compartment', 0),
(518, 'engine_bay', 'F26', 20, 'Spare fuse', 0),
(518, 'engine_bay', 'F27', 25, 'Fuse box in passenger compartment', 0),
(518, 'engine_bay', 'F28', 30, 'Selective catalytic reduction (SCR)', 0),
(518, 'engine_bay', 'F29', 40, 'Windscreen wiper', 0),
(518, 'engine_bay', 'FL30', 80, 'Preheating control unit', 0),
(518, 'engine_bay', 'FL31', 80, 'Protection and Switching unit; Passenger compartment', 0),
(518, 'engine_bay', 'FL32', 80, 'Power steering control unit', 0),
(518, 'cabin', 'F1', 40, 'Heated rear windscreen', 0),
(518, 'cabin', 'F2', 10, 'Heated mirror(s)', 0),
(518, 'cabin', 'F3', 30, 'Front power windows', 0),
(518, 'cabin', 'F4', 10, 'Control panel', 0),
(518, 'cabin', 'F5', 30, 'One-touch power windows', 0),
(518, 'cabin', 'F6', 5, 'Spare fuse', 0),
(518, 'cabin', 'F7', 30, 'Spare fuse', 0),
(518, 'cabin', 'F8', 40, 'Fuse and relay box in passenger compartment, relay R2', 0),
(518, 'cabin', 'F9', 25, 'Spare fuse', 0),
(518, 'cabin', 'F10', 30, 'Heated seats', 0),
(518, 'cabin', 'F11', 5, 'Driver''s seat adjustment comfort relay', 0),
(518, 'cabin', 'F12', 10, 'Spare fuse', 0);

-- ───────────────────────── Insignia B (520) ───────────────────────────────
INSERT INTO fuses (generation_id, location, position, amperage, circuit_name, is_relay) VALUES
(520, 'engine_bay', 'F3UA', 50, 'ABS pump', 0),
(520, 'engine_bay', 'F5UA', 60, 'DC-AC converter', 0),
(520, 'engine_bay', 'F6UA', 7.5, 'Liftgate', 0),
(520, 'engine_bay', 'F7UA', 15, 'Fog light', 0),
(520, 'engine_bay', 'F8UA', 10, 'Memory seat control unit; Mirror switch', 0),
(520, 'engine_bay', 'F9UA', 5, 'Windscreen de-icer relay', 0),
(520, 'engine_bay', 'F10UA', 10, 'Electric seats; Electric seat control unit', 0),
(520, 'engine_bay', 'F11UA', 40, 'Power supply control unit', 0),
(520, 'engine_bay', 'F12UA', 40, 'Rear windscreen defroster', 0),
(520, 'engine_bay', 'F13UA', 10, 'Exterior mirror', 0),
(520, 'engine_bay', 'F16UA', 30, 'Windscreen wiper relay', 0),
(520, 'engine_bay', 'F17UA', 30, 'Passenger''s seat control unit', 0),
(520, 'engine_bay', 'F18UA', 30, 'Sunroof motor', 0),
(520, 'engine_bay', 'F19UA', 30, 'Driver''s seat control unit', 0),
(520, 'engine_bay', 'F21UA', 30, 'Sunroof control unit', 0),
(520, 'engine_bay', 'F22UA', 20, 'Rear wiper relay', 0),
(520, 'engine_bay', 'F96UA', 30, 'Water in fuel; Fuel preheater', 0),
(520, 'engine_bay', 'F26UA', 7.5, 'Semi-automatic transmission control unit; Gearbox cooling solenoid valve', 0),
(520, 'engine_bay', 'F27UA', 10, 'Rear-view mirror; Electric additional heater; Heating, ventilation and air conditioning control unit; Collision warning; Hea', 0),
(520, 'engine_bay', 'F29UA', 10, 'Rear-view camera system; Heated seats', 0),
(520, 'engine_bay', 'F30UA', 5, 'Fuel pump control unit; Reductant control unit; Instrument cluster; Power supply', 0),
(520, 'engine_bay', 'F95UA', 15, 'Charge air cooling system', 0),
(520, 'engine_bay', 'F32UA', 10, 'Video control computer', 0),
(520, 'engine_bay', 'F33UA', 15, 'Heated seat control unit', 0),
(520, 'engine_bay', 'F34UA', 15, 'Heated rear seat control unit', 0),
(520, 'engine_bay', 'F35UA', 10, 'Suspension control unit; Differential control unit', 0),
(520, 'engine_bay', 'F36UA', 20, 'Fuel pump control unit', 0),
(520, 'engine_bay', 'F93UA', 7.5, 'Keyless entry control unit', 0),
(520, 'engine_bay', 'F40UA', 15, 'Steering column lock control unit', 0),
(520, 'engine_bay', 'F92UA', 10, 'Additional heater coolant pump relay', 0),
(520, 'engine_bay', 'F43UA', 15, 'Steering wheel heater control unit', 0),
(520, 'engine_bay', 'F44UA', 10, 'Headlight levelling control unit', 0),
(520, 'engine_bay', 'F46UA', 7.5, 'Engine control unit; Starter relay', 0),
(520, 'engine_bay', 'F48UA', 50, 'Cooling fan motor; Or; Power supply control unit; (40A also used)', 0),
(520, 'engine_bay', 'F49UA', 30, 'Differential control unit', 0),
(520, 'engine_bay', 'F56UA', 30, 'Starter relay', 0),
(520, 'engine_bay', 'F59UA', 15, 'Headlight levelling control unit', 0),
(520, 'engine_bay', 'F60UA', 50, 'Cooling fan motor', 0),
(520, 'engine_bay', 'F65UA', 10, 'Compressor clutch relay', 0),
(520, 'engine_bay', 'F69UA', 15, 'Headlight levelling control unit; Cornering light control unit; Main/dipped beam switching solenoid, right side; (10A also u', 0),
(520, 'engine_bay', 'F70UA', 10, 'Main/dipped beam switching solenoid, left side', 0),
(520, 'engine_bay', 'F88UA', 10, 'Active Air Flap module', 0),
(520, 'engine_bay', 'F72UA', 50, 'Starter solenoid; Fuel heating relay', 0),
(520, 'engine_bay', 'F74UA', 20, 'Spare fuse', 0),
(520, 'engine_bay', 'F75UA', 25, 'Engine control unit', 0),
(520, 'engine_bay', 'F76UA', 15, 'Heated oxygen sensors; Inlet air temperature sensor; Automatic transmission solenoid', 0),
(520, 'engine_bay', 'F78UA', 20, 'Horns', 0),
(520, 'engine_bay', 'F79UA', 60, 'Windscreen washer pump relay; Fuse and relay box in engine compartment, fuses 83, 84, 88', 0),
(520, 'engine_bay', 'F81UA', 7.5, 'Engine control unit', 0),
(520, 'engine_bay', 'F83UA', 15, 'Ignition coils 1 - 5; Engine control unit; Coolant thermoswitch; (7.5A also used)', 0),
(520, 'engine_bay', 'F84UA', 15, 'Heated oxygen sensors; Engine control unit; Canister purge solenoid; Turbocharger bypass valve; Wastegate control solenoid;', 0),
(520, 'engine_bay', 'F85UA', 60, 'Fuse and relay box in engine compartment, fuses 83, 84, 88', 0),
(520, 'engine_bay', 'F1UB', 500, 'Starter motor; Generator; (100A also used)', 0),
(520, 'engine_bay', 'F2UB', 100, 'Power steering control unit; Fuse and relay box in luggage compartment', 0),
(520, 'engine_bay', 'F3UB', 100, 'Electric additional heater', 0),
(520, 'engine_bay', 'F4UB', 80, 'Engine control unit', 0),
(520, 'engine_bay', 'F5UB', 80, 'Additional fuse and relay box in engine compartment', 0),
(520, 'cabin', 'F1DA', 30, 'Rear left power window motor; Driver''s side power window', 0),
(520, 'cabin', 'F2DA', 30, 'Front right power window motor; Rear right power window motor', 0),
(520, 'cabin', 'F3DA', 30, 'Body control unit; Door latch assembly; Door lock relay; Fuel filler flap lock motor; Fuel filler flap solenoid', 0),
(520, 'cabin', 'F4DA', 40, 'Blower motor control unit', 0),
(520, 'cabin', 'F5DA', 15, 'Body control unit; Door and floor lights; Roof lights; Safety and information control unit (SIM); Electric parking brake con', 0),
(520, 'cabin', 'F6DA', 15, 'Trailer connector socket', 0),
(520, 'cabin', 'F7DA', 15, 'Rear left seat control unit; Rear right seat control unit', 0),
(520, 'cabin', 'F8DA', 15, 'Body control unit; Brake lights; Parking lights; Daylight running lights, dipped beam; Light control unit', 0),
(520, 'cabin', 'F9DA', 5, 'Reductant control unit', 0),
(520, 'cabin', 'F10DA', 15, 'Heating, ventilation and air conditioning control unit; Instrument cluster; Head-up display control unit; Information displa', 0),
(520, 'cabin', 'F11DA', 30, 'Reductant control unit', 0),
(520, 'cabin', 'F12DA', 10, 'Particulate sensor; Oxygen sensor in front of the catalytic converter; Oxygen sensor behind the catalytic converter; Fuel pu', 0),
(520, 'cabin', 'F13DA', 5, 'Reductant control unit', 0),
(520, 'cabin', 'F15DA', 20, 'Transmission control unit; Gearbox solenoid', 0),
(520, 'cabin', 'F16DA', 30, 'Noise-cancelling capacitor; Audio amplifier', 0),
(520, 'cabin', 'F17DA', 10, 'Alarm control unit', 0),
(520, 'cabin', 'F18DA', 15, 'Body control unit; Rear fog light; Brake warning light; Tail lights', 0),
(520, 'cabin', 'F19DA', 10, 'Reductant control unit', 0),
(520, 'cabin', 'F20DA', 15, 'Body control unit; Radio; Overhead console; Sun sensor; Forward-view camera switch; Interior lights; Exterior lights; Fuel p', 0),
(520, 'cabin', 'F21DA', 15, 'Body control unit; Exterior lights', 0),
(520, 'cabin', 'F22DA', 15, 'Body control unit; Radio; Interior lights; Exterior lights; Trailer detection', 0),
(520, 'cabin', 'F23DA', 2, 'Steering column lock control unit', 0),
(520, 'cabin', 'F24DA', 10, 'Diagnostic control unit', 0),
(520, 'cabin', 'F25DA', 7.5, 'Data link connector', 0),
(520, 'cabin', 'F26DA', 30, 'Rear accessory socket', 0),
(520, 'cabin', 'F27DA', 40, 'Electric parking brake control unit', 0),
(520, 'cabin', 'F31DA', 2, 'Steering wheel controls', 0),
(520, 'cabin', 'F32DA', 2, 'Ignition switch', 0),
(520, 'cabin', 'F33DA', 10, 'Heating, ventilation and air conditioning control unit', 0),
(520, 'cabin', 'F34DA', 5, 'Gateway control unit', 0),
(520, 'cabin', 'F36DA', 5, 'Mobile phone wireless charger; USB', 0),
(520, 'cabin', 'F37DA', 20, 'Rear wiper motor', 0),
(520, 'cabin', 'F38DA', 5, 'Telematics control unit', 0),
(520, 'cabin', 'F39DA', 7.5, 'Heating, ventilation and air conditioning (HVAC); Instrument cluster; Information display', 0),
(520, 'cabin', 'F40DA', 10, 'Forward-view camera switch; Radar system; Parking assistance system control unit', 0),
(520, 'cabin', 'F41DA', 15, 'Centre console; Rain sensor control unit; Rear reading lights', 0),
(520, 'cabin', 'F42DA', 15, 'Radio; System interface control unit', 0);

-- citations
INSERT INTO spec_sources (spec_table, spec_id, source_id) SELECT 'fuses', id, 1682 FROM fuses WHERE generation_id = 518;
INSERT INTO spec_sources (spec_table, spec_id, source_id) SELECT 'fuses', id, 1683 FROM fuses WHERE generation_id = 520;
