#!/usr/bin/env tsx
/**
 * HaynesPro chassis-crawl → SQL migration converter.
 *
 * Takes a `haynespro-crawl-{slug}.json` (produced by crawl_chassis.js)
 * and a target catalog generation_id, emits a runnable migration file
 * with INSERT IGNORE statements for engines + fluid_specs + spec_sources.
 *
 * Usage:
 *   npx tsx scrapers/haynespro/ingest_to_sql.ts \
 *     scrapers/output/haynespro-crawl-q5-fy.json \
 *     --gen-id 82 \
 *     --slug q5-fy \
 *     [--engines DMSA,DPUA,DPVA]   # filter to specific engine codes
 *     [--mig-number 211]            # for the output filename
 *
 * Output:
 *   db/migrations/{NNN}_ingest_haynespro_{slug}.sql
 *
 * What the generated SQL does:
 *   1. INSERT IGNORE a HaynesPro source row for the chassis modelId
 *      (is_public=0, public_link=0 per [[ownerspecs-project]] policy)
 *   2. INSERT IGNORE engines for any engine_code not already in catalog
 *   3. INSERT IGNORE fluid_specs (engine_oil, coolant) per engine
 *      scoped to the target gen_id
 *   4. INSERT IGNORE spec_sources linking each new fluid_spec to the
 *      HaynesPro source
 *   5. Audit SELECT at end showing what was inserted
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type EngineRecord = {
  typeId: string;
  type: string;
  engine_code: string | null;
  cc: number | null;
  kw: number | null;
  years: string;
  oil?: { visc: string | null; spec: string | null; sump_l: number | null; drain_nm: number | null } | null;
  coolant?: { spec: string | null; capacity_l: number | null } | null;
};

type Crawl = {
  chassis: { modelId: string; label: string | null; engines_count: number; fetched_at: string };
  types: EngineRecord[];
};

function arg(flag: string): string | null {
  const i = process.argv.indexOf(flag);
  return i < 0 ? null : process.argv[i + 1];
}

function escapeSql(s: string | null): string {
  if (s == null) return "NULL";
  return "'" + s.replace(/'/g, "''") + "'";
}

function num(n: number | null | undefined): string {
  return n == null ? "NULL" : String(n);
}

function main() {
  const path = process.argv[2];
  if (!path) {
    console.error("Usage: ingest_to_sql.ts <crawl.json> --gen-id N --slug SLUG [--engines E1,E2] [--mig-number NNN]");
    process.exit(1);
  }
  const genId = arg("--gen-id");
  const slug = arg("--slug");
  const enginesFilter = arg("--engines")?.split(",").map(s => s.trim());
  const migNumber = arg("--mig-number") ?? "XXX";
  if (!genId || !slug) {
    console.error("--gen-id and --slug are required");
    process.exit(1);
  }

  const crawl: Crawl = JSON.parse(readFileSync(path, "utf8"));
  const candidates = enginesFilter
    ? crawl.types.filter(t => t.engine_code && enginesFilter.includes(t.engine_code))
    : crawl.types;
  if (candidates.length === 0) {
    console.error("No candidates after engine filter.");
    process.exit(1);
  }

  // Dedupe by engine_code — many typeIds can share an engine_code (e.g.
  // same engine across multiple years), and HaynesPro lubricants are
  // engine-code-scoped not typeId-scoped.
  const byEngine = new Map<string, EngineRecord>();
  for (const t of candidates) {
    if (!t.engine_code) continue;
    if (!byEngine.has(t.engine_code)) byEngine.set(t.engine_code, t);
  }

  const lines: string[] = [];
  lines.push(`-- HaynesPro chassis crawl → catalog ingest`);
  lines.push(`-- Source crawl: ${path}`);
  lines.push(`-- HaynesPro modelId: ${crawl.chassis.modelId} (${crawl.chassis.label ?? '?'})`);
  lines.push(`-- Crawl fetched_at: ${crawl.chassis.fetched_at}`);
  lines.push(`-- Target catalog generation_id: ${genId}`);
  lines.push(`-- Engines: ${[...byEngine.keys()].join(', ')}`);
  lines.push(`-- Generated by scrapers/haynespro/ingest_to_sql.ts on ${new Date().toISOString()}`);
  lines.push("");
  lines.push("SET NAMES utf8mb4;");
  lines.push("");

  // 1) HaynesPro source row
  const haynesUrl = `https://www.workshopdata.com/touch/site/layout/modelTypesList?modelId=${crawl.chassis.modelId}`;
  const haynesCitation = `HaynesPro WorkshopData — ${crawl.chassis.label ?? crawl.chassis.modelId}`;
  lines.push("-- 1. HaynesPro source row (is_public=0, citation only for audit trail)");
  lines.push(`INSERT IGNORE INTO sources (citation, url, retrieved_at, notes, is_public, public_link) VALUES`);
  lines.push(`  (${escapeSql(haynesCitation)}, ${escapeSql(haynesUrl)}, NOW(), ${escapeSql(`Auto-ingested via scrapers/haynespro/ingest_to_sql.ts. modelId ${crawl.chassis.modelId}, ${candidates.length} engines crawled, ${byEngine.size} unique engine codes ingested.`)}, 0, 0);`);
  lines.push(`SET @s_haynes := (SELECT id FROM sources WHERE url = ${escapeSql(haynesUrl)} ORDER BY id DESC LIMIT 1);`);
  lines.push("");

  // 2) Engines — INSERT IGNORE for new ones
  lines.push("-- 2. Engines — auto-insert any not yet in catalog");
  lines.push("INSERT IGNORE INTO engines (code, display_name, displacement_cc, fuel, aspiration, cylinders) VALUES");
  const engineRows: string[] = [];
  for (const t of byEngine.values()) {
    const isPetrol = /TFSI|TSI|TGI|GTI|petrol/i.test(t.type);
    const isDiesel = /TDI|diesel|HDi|BlueTec|d$/i.test(t.type);
    const isHybrid = /TFSI e|hybrid|e-tron|MHEV|eTDI/i.test(t.type);
    const fuel = isHybrid ? 'hybrid' : isDiesel ? 'diesel' : isPetrol ? 'petrol' : 'petrol';
    const aspiration = /TFSI|TSI|TDI|turbo/i.test(t.type) ? 'turbo' : 'NA';
    const display = `${t.type ?? ''} (${t.engine_code}) ${t.kw ? t.kw + 'kW' : ''}`.trim().replace(/\s+/g, ' ');
    engineRows.push(`  (${escapeSql(t.engine_code)}, ${escapeSql(display)}, ${num(t.cc)}, ${escapeSql(fuel)}, ${escapeSql(aspiration)}, NULL)`);
  }
  lines.push(engineRows.join(",\n") + ";");
  lines.push("");

  // 3) fluid_specs — engine_oil + coolant per engine
  lines.push("-- 3. fluid_specs — engine_oil + coolant scoped to gen_id " + genId);
  lines.push(`SET @gen := ${genId};`);
  lines.push("");
  const fsRows: string[] = [];
  for (const t of byEngine.values()) {
    const eIdLookup = `(SELECT id FROM engines WHERE code = ${escapeSql(t.engine_code)})`;
    if (t.oil && (t.oil.sump_l != null || t.oil.spec)) {
      const capQt = t.oil.sump_l != null ? Math.round(t.oil.sump_l * 1.05669 * 100) / 100 : null;
      fsRows.push(
        `(@gen, 'engine_oil', ${eIdLookup}, ${num(t.oil.sump_l)}, ${num(capQt)}, ${escapeSql(t.oil.visc)}, ${escapeSql(t.oil.spec)}, ${escapeSql(`HaynesPro typeId ${t.typeId}; ${t.type}; drain ${t.oil.drain_nm ?? '?'} Nm`)})`,
      );
    }
    if (t.coolant && (t.coolant.capacity_l != null || t.coolant.spec)) {
      const capQt = t.coolant.capacity_l != null ? Math.round(t.coolant.capacity_l * 1.05669 * 100) / 100 : null;
      fsRows.push(
        `(@gen, 'coolant', ${eIdLookup}, ${num(t.coolant.capacity_l)}, ${num(capQt)}, NULL, ${escapeSql(t.coolant.spec)}, ${escapeSql(`HaynesPro typeId ${t.typeId}; ${t.type}`)})`,
      );
    }
  }
  if (fsRows.length > 0) {
    lines.push("INSERT IGNORE INTO fluid_specs (generation_id, fluid_type, engine_id, capacity_l, capacity_qt, viscosity, spec_standard, notes) VALUES");
    lines.push(fsRows.join(",\n") + ";");
    lines.push("");
  } else {
    lines.push("-- (no fluid_specs to insert)");
    lines.push("");
  }

  // 4) spec_sources — link each fluid_specs row to HaynesPro
  lines.push("-- 4. spec_sources — link inserted fluid_specs rows to the HaynesPro source");
  lines.push(`INSERT IGNORE INTO spec_sources (spec_table, spec_id, source_id)`);
  lines.push(`SELECT 'fluid_specs', fs.id, @s_haynes`);
  lines.push(`FROM fluid_specs fs`);
  lines.push(`JOIN engines e ON e.id = fs.engine_id`);
  lines.push(`WHERE fs.generation_id = @gen`);
  lines.push(`  AND e.code IN (${[...byEngine.keys()].map(escapeSql).join(", ")})`);
  lines.push(`  AND fs.fluid_type IN ('engine_oil', 'coolant');`);
  lines.push("");

  // 5) Audit
  lines.push("-- 5. Audit");
  lines.push(`SELECT e.code, COUNT(fs.id) AS rows_count,`);
  lines.push(`       GROUP_CONCAT(DISTINCT CONCAT(fs.fluid_type, ' ', fs.capacity_l, 'L ', COALESCE(fs.viscosity,''), ' ', COALESCE(fs.spec_standard,'')) SEPARATOR ' | ') AS specs`);
  lines.push(`FROM fluid_specs fs`);
  lines.push(`JOIN engines e ON e.id = fs.engine_id`);
  lines.push(`WHERE fs.generation_id = @gen`);
  lines.push(`  AND e.code IN (${[...byEngine.keys()].map(escapeSql).join(", ")})`);
  lines.push(`GROUP BY e.code ORDER BY e.code;`);
  lines.push("");

  const outName = `${migNumber}_ingest_haynespro_${slug}.sql`;
  const outPath = resolve(process.cwd(), `db/migrations/${outName}`);
  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
  console.log(`Engines: ${byEngine.size} unique | fluid_specs rows planned: ${fsRows.length}`);
}

main();
